spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ichigo
    password: ichigo
    url: jdbc:mysql://localhost:3306/ichigo_db
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
